---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1
  - name: centos-6.7

suites:
  - name: default
    data_bags_path: test/integration/data_bags
    run_list:
      - recipe[data-bag-faker]
      - recipe[sumologic-collector::default]
    attributes:
      SUMO_ACCESS_ID: <%= ENV['SUMO_ACCESS_ID'] %>
      SUMO_ACCESS_KEY: <%= ENV['SUMO_ACCESS_KEY'] %>